name: Construir artefacto
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout del código fuente
        uses: actions/checkout@v2

      - name: Artefacto Cliente
        run: |
            cd Practica4/cliente
            npm install
            npm run build
            npm pack
      
      - name: Artefacto Restaurante
        run: |
            cd Practica4/restaurante
            npm install
            npm run build
            npm pack
      
      - name: Artefacto Repartidor
        run: |
            cd Practica4/repartidor
            npm install
            npm run build
            npm pack
      
      - name: Artefacto ESB
        run: |
            cd Practica4/esb
            npm install
            npm run build
            npm pack
